apiVersion: apps/v1
kind: Deployment
metadata:
  name: wts
  labels:
    app: wts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wts
  template:
    metadata:
      labels:
        app: wts
    spec:
      containers:
        - name: wts
          image: skcchhson.azurecr.io/wts:latest
          volumeMounts:
            - mountPath: "/data"
              name: wts-vol
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
      volumes:
        - name: wts-vol
          persistentVolumeClaim:
            claimName: wts-pvc